# Generated by Django 5.1.7 on 2025-06-22 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_image_description_image_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='music/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('serenity', 'Serenity'), ('romantic', 'Romantic'), ('inspiration', 'Inspiration'), ('focus', 'Focus'), ('meditation', 'Meditation')], max_length=20, unique=True)),
                ('admin_collections', models.ManyToManyField(blank=True, related_name='admin_modes', to='gallery.collection')),
                ('admin_music', models.ManyToManyField(blank=True, related_name='admin_modes', to='modes.music')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('purpose', models.CharField(choices=[('focus', 'Focus'), ('sleep', 'Sleep'), ('calm', 'Calm'), ('mindfulness', 'Mindfulness')], max_length=20)),
                ('intention', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='modes.mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customizations', to='modes.mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modes', to=settings.AUTH_USER_MODEL)),
                ('user_collections', models.ManyToManyField(blank=True, related_name='user_modes', to='gallery.collection')),
                ('user_music', models.ManyToManyField(blank=True, related_name='user_modes', to='modes.music')),
            ],
            options={
                'unique_together': {('user', 'mode')},
            },
        ),
    ]
