# Generated by Django 5.1.7 on 2025-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_description_image_title'),
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='admin_curations',
            field=models.ManyToManyField(blank=True, related_name='curated_modes', to='gallery.collection'),
        ),
    ]
