# Generated by Django 5.1.7 on 2025-06-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0002_mode_admin_curations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(choices=[('serenity', 'Serenity'), ('romantic', 'Romantic'), ('inspiration', 'Inspiration'), ('dance', 'Dance'), ('meditation', 'Meditation')], max_length=20, unique=True),
        ),
    ]
