# Generated by Django 5.1.7 on 2025-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_audio_music_cover'),
        ('modes', '0003_alter_mode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermode',
            name='user_music',
            field=models.ManyToManyField(blank=True, related_name='user_modes', to='gallery.audio'),
        ),
    ]
