# Generated by Django 5.1.7 on 2025-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0004_alter_usermode_user_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(choices=[('serenity', 'Serenity'), ('romantic', 'Romantic'), ('inspiration', 'Inspiration'), ('dance', 'Dance'), ('meditation', 'Meditation'), ('creative', 'Creative')], max_length=20, unique=True),
        ),
    ]
