# Generated by Django 5.1.7 on 2025-05-01 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('transcription', 'Transcription'), ('analysis', 'Analysis'), ('summarization', 'Summarization'), ('image_generation', 'Image Generation'), ('image_editing', 'Image Editing')], max_length=30)),
                ('provider', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'indexes': [models.Index(fields=['model_type'], name='ai_models_model_t_608c1f_idx'), models.Index(fields=['provider'], name='ai_models_provide_04108a_idx'), models.Index(fields=['is_active'], name='ai_models_is_acti_b1b072_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('transcription', 'Audio Transcription'), ('analysis', 'Transcript Analysis'), ('summarization', 'Text Summarization'), ('image_generation', 'Image Generation'), ('image_editing', 'Image Editing')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_integration.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Operation',
                'verbose_name_plural': 'AI Operations',
                'db_table': 'ai_operations',
            },
        ),
        migrations.CreateModel(
            name='AICallback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='ai_integration.aioperation')),
            ],
            options={
                'verbose_name': 'AI Callback',
                'verbose_name_plural': 'AI Callbacks',
                'db_table': 'ai_callbacks',
            },
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['user'], name='ai_operatio_user_id_e3e07c_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['operation_type'], name='ai_operatio_operati_8fb605_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['status'], name='ai_operatio_status_30af77_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['created_at'], name='ai_operatio_created_ea5fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['operation'], name='ai_callback_operati_4c5a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['processed'], name='ai_callback_process_84f2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['created_at'], name='ai_callback_created_a9bd89_idx'),
        ),
    ]
