# Generated by Django 5.1.7 on 2025-05-03 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aioperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicallback',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='ai_integration.aioperation'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['user'], name='ai_operatio_user_id_e3e07c_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['operation_type'], name='ai_operatio_operati_8fb605_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['status'], name='ai_operatio_status_30af77_idx'),
        ),
        migrations.AddIndex(
            model_name='aioperation',
            index=models.Index(fields=['created_at'], name='ai_operatio_created_ea5fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['operation'], name='ai_callback_operati_4c5a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['processed'], name='ai_callback_process_84f2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='aicallback',
            index=models.Index(fields=['created_at'], name='ai_callback_created_a9bd89_idx'),
        ),
    ]
