# Generated by Django 5.1.7 on 2025-12-07 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNarration',
            fields=[
                ('narration_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing_images', 'Processing Images'), ('processing_video', 'Processing Video'), ('generating_script', 'Generating Script'), ('generating_voice', 'Generating Voice'), ('creating_video', 'Creating Video'), ('adding_audio', 'Adding Audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('input_type', models.CharField(choices=[('images', 'Images'), ('video', 'Video')], default='images', max_length=20)),
                ('script', models.TextField(blank=True, null=True)),
                ('audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('final_video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('video_duration', models.FloatField(blank=True, null=True)),
                ('download_url', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collection_narrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='collection__user_id_decb0c_idx'), models.Index(fields=['status'], name='collection__status_a8fc92_idx'), models.Index(fields=['created_at'], name='collection__created_e88b4f_idx')],
            },
        ),
    ]
