# Generated by Django 5.1.7 on 2026-01-24 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VizzyChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional session title (auto-generated or user-set)', max_length=255, null=True)),
                ('mode', models.CharField(choices=[('home', 'Home Mode'), ('enterprise', 'Enterprise Mode')], default='home', help_text='Chat mode: home (casual) or enterprise (professional)', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Session creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Session closure timestamp', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of last message in session', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Cached count of messages in session', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(help_text='Session owner', on_delete=django.db.models.deletion.CASCADE, related_name='vizzy_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizzy Chat Session',
                'verbose_name_plural': 'Vizzy Chat Sessions',
                'db_table': 'vizzy_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VizzyChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique message identifier', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Vizzy'), ('system', 'System')], db_index=True, help_text='Message sender role', max_length=20)),
                ('content', models.TextField(help_text='Message content (text)')),
                ('has_images', models.BooleanField(db_index=True, default=False, help_text='Whether message includes images')),
                ('image_urls', models.JSONField(blank=True, default=list, help_text='List of S3 URLs for images (if any)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Message creation timestamp')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used in LLM processing', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('detected_emotion', models.CharField(blank=True, help_text='Detected emotion label (joy, calm, stress, etc.)', max_length=50, null=True)),
                ('mood_valence', models.FloatField(blank=True, help_text='Emotional valence: -1 (negative) to 1 (positive)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mood_arousal', models.FloatField(blank=True, help_text='Emotional arousal: -1 (low energy) to 1 (high energy)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session', models.ForeignKey(help_text='Parent session', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vizzy_chat.vizzychatsession')),
            ],
            options={
                'verbose_name': 'Vizzy Chat Message',
                'verbose_name_plural': 'Vizzy Chat Messages',
                'db_table': 'vizzy_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VizzyUserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vizzy_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aesthetic_palette', models.JSONField(blank=True, default=dict, help_text="User's aesthetic preferences (colors, styles, themes)")),
                ('mood_map', models.JSONField(blank=True, default=dict, help_text='Historical mood patterns and trends')),
                ('story_markers', models.JSONField(blank=True, default=list, help_text='Important memories, milestones, and life events')),
                ('device_context', models.JSONField(blank=True, default=dict, help_text='Device configuration (room types, display schedule, etc.)')),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of chat sessions', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_messages', models.IntegerField(default=0, help_text='Total number of messages sent', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_active', models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp')),
            ],
            options={
                'verbose_name': 'Vizzy User Profile',
                'verbose_name_plural': 'Vizzy User Profiles',
                'db_table': 'vizzy_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='VizzyMoodHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique mood entry identifier', primary_key=True, serialize=False)),
                ('valence', models.FloatField(help_text='Emotional valence: -1 (negative) to 1 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('arousal', models.FloatField(help_text='Emotional arousal: -1 (low energy) to 1 (high energy)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('emotion_label', models.CharField(help_text='Emotion label (joy, calm, stress, anger, etc.)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When mood was recorded')),
                ('source', models.CharField(choices=[('text_analysis', 'Text Analysis'), ('explicit_input', 'Explicit User Input'), ('image_analysis', 'Image Analysis'), ('context_inference', 'Context Inference')], help_text='How mood was determined', max_length=50)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score for mood detection (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session', models.ForeignKey(blank=True, help_text='Associated session (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='vizzy_chat.vizzychatsession')),
                ('user', models.ForeignKey(help_text='User whose mood is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='vizzy_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizzy Mood History',
                'verbose_name_plural': 'Vizzy Mood Histories',
                'db_table': 'vizzy_mood_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VizzyContextData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique context entry identifier', primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('preference', 'User Preference'), ('creation', 'Past Creation'), ('interaction', 'Interaction Pattern'), ('knowledge', 'Domain Knowledge'), ('metadata', 'Metadata')], db_index=True, help_text='Type of context data', max_length=50)),
                ('key', models.CharField(db_index=True, help_text="Context key (e.g., 'favorite_color', 'preferred_style')", max_length=255)),
                ('value', models.JSONField(help_text='Context value (flexible JSON structure)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When context was created')),
                ('accessed_at', models.DateTimeField(auto_now=True, help_text='Last access timestamp')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times accessed', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(help_text='Context owner', on_delete=django.db.models.deletion.CASCADE, related_name='vizzy_context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizzy Context Data',
                'verbose_name_plural': 'Vizzy Context Data',
                'db_table': 'vizzy_context_data',
                'ordering': ['-accessed_at'],
                'unique_together': {('user', 'context_type', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='vizzychatsession',
            index=models.Index(fields=['user', '-created_at'], name='vizzy_sess_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatsession',
            index=models.Index(fields=['is_active', '-updated_at'], name='vizzy_sess_active_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatsession',
            index=models.Index(fields=['-updated_at'], name='vizzy_sess_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatmessage',
            index=models.Index(fields=['session', 'created_at'], name='vizzy_msg_sess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatmessage',
            index=models.Index(fields=['role', 'created_at'], name='vizzy_msg_role_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatmessage',
            index=models.Index(fields=['has_images'], name='vizzy_msg_has_images_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzychatmessage',
            index=models.Index(fields=['-created_at'], name='vizzy_msg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzymoodhistory',
            index=models.Index(fields=['user', '-timestamp'], name='vizzy_mood_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzymoodhistory',
            index=models.Index(fields=['session', '-timestamp'], name='vizzy_mood_sess_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzymoodhistory',
            index=models.Index(fields=['emotion_label'], name='vizzy_mood_label_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzymoodhistory',
            index=models.Index(fields=['-timestamp'], name='vizzy_mood_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzycontextdata',
            index=models.Index(fields=['user', 'context_type'], name='vizzy_ctx_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzycontextdata',
            index=models.Index(fields=['key'], name='vizzy_ctx_key_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzycontextdata',
            index=models.Index(fields=['user', 'key'], name='vizzy_ctx_user_key_idx'),
        ),
        migrations.AddIndex(
            model_name='vizzycontextdata',
            index=models.Index(fields=['-accessed_at'], name='vizzy_ctx_accessed_idx'),
        ),
    ]
