# Generated by Django 5.1.7 on 2025-12-17 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('prompt', models.TextField(help_text='Generation prompt used')),
                ('width', models.IntegerField(default=1024, validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(2048)])),
                ('height', models.IntegerField(default=1024, validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(2048)])),
                ('style_preset', models.CharField(default='cinematic', max_length=100)),
                ('s3_url', models.URLField(blank=True, help_text='S3 URL if uploaded', null=True)),
                ('s3_key', models.CharField(blank=True, help_text='S3 bucket key', max_length=500, null=True)),
                ('local_url', models.URLField(help_text='Local URL fallback')),
                ('service', models.CharField(choices=[('runware', 'Runware'), ('user_uploaded', 'User Uploaded')], default='runware', max_length=50)),
                ('model', models.CharField(blank=True, help_text='AI model used', max_length=100, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotePoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('quote_text', models.TextField(help_text='Quote text displayed on poster')),
                ('font_family', models.CharField(default='arial', max_length=100)),
                ('font_size', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('font_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('square', 'Square')], default='horizontal', max_length=15)),
                ('opacity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('shadow', models.BooleanField(default=True, help_text='Add shadow to text')),
                ('s3_url', models.URLField(blank=True, help_text='S3 URL if uploaded', null=True)),
                ('s3_key', models.CharField(blank=True, help_text='S3 bucket key', max_length=500, null=True)),
                ('local_url', models.URLField(help_text='Local URL fallback')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('share_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='quote_poster.background')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_posters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_url', models.URLField(db_index=True, unique=True)),
                ('share_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='quote_poster.quoteposter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, help_text='Rating 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='quote_poster.quoteposter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='background',
            index=models.Index(fields=['user', '-created_at'], name='quote_poste_user_id_99a60a_idx'),
        ),
        migrations.AddIndex(
            model_name='background',
            index=models.Index(fields=['status'], name='quote_poste_status_f4124e_idx'),
        ),
        migrations.AddIndex(
            model_name='background',
            index=models.Index(fields=['session_id'], name='quote_poste_session_20fcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteposter',
            index=models.Index(fields=['user', '-created_at'], name='quote_poste_user_id_3ce9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteposter',
            index=models.Index(fields=['status'], name='quote_poste_status_5a9b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteposter',
            index=models.Index(fields=['session_id'], name='quote_poste_session_76d6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteposter',
            index=models.Index(fields=['is_public'], name='quote_poste_is_publ_b1065c_idx'),
        ),
        migrations.AddIndex(
            model_name='postershare',
            index=models.Index(fields=['share_token'], name='quote_poste_share_t_9d658c_idx'),
        ),
        migrations.AddIndex(
            model_name='postershare',
            index=models.Index(fields=['poster'], name='quote_poste_poster__7210eb_idx'),
        ),
        migrations.AddIndex(
            model_name='posterfeedback',
            index=models.Index(fields=['poster'], name='quote_poste_poster__bf5b47_idx'),
        ),
        migrations.AddIndex(
            model_name='posterfeedback',
            index=models.Index(fields=['user'], name='quote_poste_user_id_3bf4cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posterfeedback',
            unique_together={('poster', 'user')},
        ),
    ]
