# Generated by Django 5.1.7 on 2025-04-14 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_time', models.IntegerField(default=10, help_text='Time in seconds to display each image')),
                ('music_preference', models.CharField(blank=True, max_length=255)),
                ('meta_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_images', to='gallery.collection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_collections', to='gallery.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('favorite', 'Favorite')], max_length=10)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='gallery.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user'], name='gallery_col_user_id_c068ef_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_by'], name='gallery_ima_uploade_d721ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionimage',
            unique_together={('collection', 'image')},
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['user'], name='gallery_ima_user_id_d9efb0_idx'),
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['image'], name='gallery_ima_image_i_e2e853_idx'),
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['external_image_id'], name='gallery_ima_externa_186b7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('image__isnull', False)), fields=('user', 'image', 'interaction_type'), name='unique_internal_image_interaction'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_image_id__isnull', False)), fields=('user', 'external_image_id', 'interaction_type'), name='unique_external_image_interaction'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_image_id__isnull', True), ('image__isnull', False)), models.Q(('external_image_id__isnull', False), ('image__isnull', True)), _connector='OR'), name='either_internal_or_external_image'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['user'], name='gallery_met_user_id_0bb46f_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['image'], name='gallery_met_image_i_709b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['external_image_id'], name='gallery_met_externa_64d959_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['created_at'], name='gallery_met_created_3febb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='metacomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_image_id__isnull', True), ('image__isnull', False)), models.Q(('external_image_id__isnull', False), ('image__isnull', True)), _connector='OR'), name='comment_either_internal_or_external_image'),
        ),
    ]
