# Generated by Django 5.1.7 on 2025-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
