# Generated by Django 5.1.7 on 2025-04-24 12:25

from apps.utils.user_directory import user_image_path,user_music_path
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=user_music_path),
        ),
        migrations.AddField(
            model_name='collection',
            name='view',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionimage',
            name='view',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=user_music_path),
        ),
        migrations.AddField(
            model_name='image',
            name='view',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=user_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
