# Generated by Django 5.1.7 on 2025-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_collection_music_collection_view_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='collectionimage',
            options={'ordering': ['order'], 'verbose_name': 'Collection Image', 'verbose_name_plural': 'Collection Images'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='imageinteraction',
            options={'verbose_name': 'Image Interaction', 'verbose_name_plural': 'Image Interactions'},
        ),
        migrations.AlterModelOptions(
            name='metacomment',
            options={'verbose_name': 'Meta Comment', 'verbose_name_plural': 'Meta Comments'},
        ),
        migrations.RenameIndex(
            model_name='collection',
            new_name='collections_user_id_b77b43_idx',
            old_name='gallery_col_user_id_c068ef_idx',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='images_uploade_6bd8cd_idx',
            old_name='gallery_ima_uploade_d721ba_idx',
        ),
        migrations.RenameIndex(
            model_name='imageinteraction',
            new_name='image_inter_user_id_2d6b44_idx',
            old_name='gallery_ima_user_id_d9efb0_idx',
        ),
        migrations.RenameIndex(
            model_name='imageinteraction',
            new_name='image_inter_image_i_04c080_idx',
            old_name='gallery_ima_image_i_e2e853_idx',
        ),
        migrations.RenameIndex(
            model_name='imageinteraction',
            new_name='image_inter_externa_3885a0_idx',
            old_name='gallery_ima_externa_186b7a_idx',
        ),
        migrations.RenameIndex(
            model_name='metacomment',
            new_name='meta_commen_user_id_479cc3_idx',
            old_name='gallery_met_user_id_0bb46f_idx',
        ),
        migrations.RenameIndex(
            model_name='metacomment',
            new_name='meta_commen_image_i_213137_idx',
            old_name='gallery_met_image_i_709b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='metacomment',
            new_name='meta_commen_externa_08e2d1_idx',
            old_name='gallery_met_externa_64d959_idx',
        ),
        migrations.RenameIndex(
            model_name='metacomment',
            new_name='meta_commen_created_239f32_idx',
            old_name='gallery_met_created_3febb9_idx',
        ),
        migrations.AlterModelTable(
            name='collection',
            table='collections',
        ),
        migrations.AlterModelTable(
            name='collectionimage',
            table='collection_images',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='imageinteraction',
            table='image_interactions',
        ),
        migrations.AlterModelTable(
            name='metacomment',
            table='meta_comments',
        ),
    ]
