# Generated by Django 5.1.7 on 2025-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedding_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
