# Generated by Django 5.1.7 on 2025-04-30 08:20

import apps.utils.user_directory._user_directory_path
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_collection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('transcript_url', models.URLField(blank=True, null=True)),
                ('transcript_status', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=255, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.utils.user_directory._user_directory_path.user_audio_path)),
                ('view', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'db_table': 'audios',
                'indexes': [models.Index(fields=['uploaded_by'], name='audios_uploade_ed78e5_idx')],
            },
        ),
    ]
