# Generated by Django 5.1.7 on 2025-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_collection_description_collection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
