# Generated by Django 5.1.7 on 2025-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the audio was last processed', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of retries for failed processing'),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript_insights',
            field=models.JSONField(blank=True, help_text='Full analysis results as JSON', null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript_sentiment',
            field=models.CharField(blank=True, help_text='Overall sentiment of the transcript', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript_summary',
            field=models.TextField(blank=True, help_text='Summary of the transcript', null=True),
        ),
    ]
