# Generated by Django 5.1.7 on 2025-06-23 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_description_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('collections', models.ManyToManyField(related_name='daily_curations', to='gallery.collection')),
            ],
            options={
                'verbose_name': 'Daily Curation',
                'verbose_name_plural': 'Daily Curations',
                'ordering': ['-date'],
            },
        ),
    ]
