# Generated by Django 5.1.7 on 2025-07-01 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_dailycuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time_of_day', models.TimeField(help_text='Time of day when the ritual is triggered')),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False, help_text='True for admin/global rituals, False for user-defined rituals')),
                ('collections', models.ManyToManyField(related_name='rituals', to='gallery.collection')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null for global rituals, set for user-defined rituals', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ritual',
                'verbose_name_plural': 'Rituals',
                'db_table': 'rituals',
                'indexes': [models.Index(fields=['is_global', 'created_by', 'time_of_day'], name='rituals_is_glob_e52a2d_idx')],
            },
        ),
    ]
