# Generated by Django 5.1.7 on 2025-07-07 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_audio_audio_alter_collection_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyImageCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('images', models.ManyToManyField(related_name='daily_image_curations', to='gallery.image')),
            ],
            options={
                'verbose_name': 'Daily Image Curation',
                'verbose_name_plural': 'Daily Image Curations',
                'ordering': ['-date'],
            },
        ),
    ]
