# Generated by Django 5.1.7 on 2025-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_dailyimagecuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='description_and_meta_notes',
            field=models.TextField(blank=True, help_text='Description and meta notes for the ritual.', null=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='repeat_details',
            field=models.JSONField(blank=True, help_text="Details for repeat: For weekly, provide 'weekdays' (list of 0-6); for monthly, 'monthday' (1-31); for yearly, 'month' (1-12) and 'day' (1-31). Leave empty for daily. Edge cases: If a day does not exist (e.g., Feb 30), skip or trigger on last valid day.", null=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='How often the ritual repeats.', max_length=10),
        ),
    ]
