# Generated by Django 5.1.7 on 2025-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_ritual_description_and_meta_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='track_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
