# Generated by Django 5.1.7 on 2025-07-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_collection_music_title'),
        ('gallery', '0011_audio_description_audio_genre_audio_track_title'),
    ]

    operations = [
    ]
