# Generated by Django 5.1.7 on 2025-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_audio_music_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
