# Generated by Django 5.1.7 on 2025-12-06 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('sunrise', 'Sunrise'), ('sunset', 'Sunset'), ('custom_time', 'Custom Time'), ('occasion', 'Occasion'), ('audience', 'Audience Trigger')], db_index=True, max_length=50)),
                ('trigger_time', models.CharField(max_length=10)),
                ('trigger_time_local', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('hourly', 'Hourly'), ('interval', 'Interval'), ('once', 'Once')], db_index=True, max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('max_executions', models.IntegerField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('visual_config', models.JSONField(default=dict)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_error_time', models.DateTimeField(blank=True, null=True)),
                ('generated_image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='events_user_id_137ee1_idx'), models.Index(fields=['enabled', 'event_type'], name='events_enabled_2ccb0f_idx'), models.Index(fields=['schedule_type'], name='events_schedul_412769_idx')],
            },
        ),
    ]
