# Generated by Django 5.1.7 on 2025-12-12 02:04

import apps.event_scheduler.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visual_config',
            field=apps.event_scheduler.models.SafeJSONField(default=dict),
        ),
    ]
