# Generated by Django 5.1.7 on 2025-04-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
