#art styles and effects for dropdown menu - to be expanded 
#Meta Prompt Template

prompt_for_style_transfer = "Transform the input image into a detailed and high-quality artwork in the style of {style_name}. Preserve the core subject and composition of the original image, but reimagine it fully using the defining visual elements, color palettes, brushwork, textures, and atmosphere characteristic of {style_name}. Ensure that the transformation is visually rich, coherent, and reflects the aesthetic language and mood of {style_name}. Output should feel as if originally created in that style."

# example prompt: Transform the input image into a detailed and high-quality artwork in the style of Art Nouveau. Preserve the core subject and composition of the original image, but reimagine it fully using the defining visual elements, color palettes, brushwork, textures, and atmosphere characteristic of Art Nouveau. Ensure that the transformation is visually rich, coherent, and reflects the aesthetic language and mood of Art Nouveau. Output should feel as if originally created in that style.
'''Optional Enhancements
You can add these elements depending on the context or UX:

🎨 With Mood Input:
... Reflect a {user_mood} atmosphere within the composition if possible.
🧠 With AI-Guided Personalization:
... Incorporate subtle personalized nuances based on the user’s profile while remaining true to the {style_name} style.
📏 With Output Constraints:
... Generate in a {resolution} aspect ratio with a focus on clarity, artistic depth, and visual balance.'''

art_style = 
{ "artStyles": [
    { "id": 1, "name": "Abstract", "category": "Modern" },
    { "id": 2, "name": "Impressionism", "category": "Classical" },
    { "id": 3, "name": "Surrealism", "category": "Modern" },
    { "id": 4, "name": "Cubism", "category": "Modern" },
    { "id": 5, "name": "Expressionism", "category": "Modern" },
    { "id": 6, "name": "Realism", "category": "Classical" },
    { "id": 7, "name": "Hyperrealism", "category": "Contemporary" },
    { "id": 8, "name": "Minimalism", "category": "Contemporary" },
    { "id": 9, "name": "Pop Art", "category": "Modern" },
    { "id": 10, "name": "Modernism", "category": "Modern" },
    { "id": 11, "name": "Postmodernism", "category": "Contemporary" },
    { "id": 12, "name": "Art Nouveau", "category": "Decorative" },
    { "id": 13, "name": "Art Deco", "category": "Decorative" },
    { "id": 14, "name": "Baroque", "category": "Classical" },
    { "id": 15, "name": "Rococo", "category": "Classical" },
    { "id": 16, "name": "Renaissance", "category": "Classical" },
    { "id": 17, "name": "Neoclassicism", "category": "Classical" },
    { "id": 18, "name": "Romanticism", "category": "Classical" },
    { "id": 19, "name": "Futurism", "category": "Modern" },
    { "id": 20, "name": "Dadaism", "category": "Modern" },
    { "id": 21, "name": "Fauvism", "category": "Modern" },
    { "id": 22, "name": "Pointillism", "category": "Classical" },
    { "id": 23, "name": "Symbolism", "category": "Classical" },
    { "id": 24, "name": "Naïve Art", "category": "Folk" },
    { "id": 25, "name": "Constructivism", "category": "Modern" },
    { "id": 26, "name": "Bauhaus", "category": "Modern" },
    { "id": 27, "name": "Suprematism", "category": "Modern" },
    { "id": 28, "name": "Vorticism", "category": "Modern" },
    { "id": 29, "name": "Brutalism", "category": "Modern" },
    { "id": 30, "name": "Conceptual Art", "category": "Contemporary" },
    { "id": 31, "name": "Kinetic Art", "category": "Modern" },
    { "id": 32, "name": "Digital Glitch", "category": "Digital" },
    { "id": 33, "name": "Vaporwave", "category": "Digital" },
    { "id": 34, "name": "Cyberpunk", "category": "Digital" },
    { "id": 35, "name": "Steampunk", "category": "Fantasy" },
    { "id": 36, "name": "Sci-fi Retro", "category": "Fantasy" },
    { "id": 37, "name": "Synthwave", "category": "Digital" },
    { "id": 38, "name": "Pixel Art", "category": "Digital" },
    { "id": 39, "name": "Low Poly", "category": "Digital" },
    { "id": 40, "name": "Isometric", "category": "Digital" },
    { "id": 41, "name": "Flat Design", "category": "Digital" },
    { "id": 42, "name": "3D Rendered", "category": "Digital" },
    { "id": 43, "name": "Photorealism", "category": "Contemporary" },
    { "id": 44, "name": "Generative Art", "category": "AI" },
    { "id": 45, "name": "AI Collage", "category": "AI" },
    { "id": 46, "name": "Data-Driven Art", "category": "AI" },
    { "id": 47, "name": "Neural Dream", "category": "AI" },
    { "id": 48, "name": "GAN Art", "category": "AI" },
    { "id": 49, "name": "Motion Blur Style", "category": "Effect" },
    { "id": 50, "name": "Chromatic Aberration", "category": "Effect" },
    { "id": 51, "name": "Watercolor", "category": "Traditional" },
    { "id": 52, "name": "Oil Painting", "category": "Traditional" },
    { "id": 53, "name": "Charcoal Sketch", "category": "Traditional" },
    { "id": 54, "name": "Pencil Drawing", "category": "Traditional" },
    { "id": 55, "name": "Ink Wash", "category": "Traditional" },
    { "id": 56, "name": "Gouache", "category": "Traditional" },
    { "id": 57, "name": "Pastel", "category": "Traditional" },
    { "id": 58, "name": "Acrylic", "category": "Traditional" },
    { "id": 59, "name": "Spray Paint", "category": "Street" },
    { "id": 60, "name": "Graffiti", "category": "Street" },
    { "id": 61, "name": "Collage", "category": "Mixed Media" },
    { "id": 62, "name": "Mixed Media", "category": "Mixed Media" },
    { "id": 63, "name": "Paper Cut", "category": "Craft" },
    { "id": 64, "name": "Origami-Inspired", "category": "Craft" },
    { "id": 65, "name": "Mosaic", "category": "Decorative" },
    { "id": 66, "name": "Stained Glass", "category": "Decorative" },
    { "id": 67, "name": "Fresco", "category": "Classical" },
    { "id": 68, "name": "Monochrome", "category": "Effect" },
    { "id": 69, "name": "Duotone", "category": "Effect" },
    { "id": 70, "name": "Neon Style", "category": "Digital" },
    { "id": 71, "name": "Psychedelic", "category": "Fantasy" },
    { "id": 72, "name": "Trippy Abstract", "category": "Fantasy" },
    { "id": 73, "name": "Liquid Flow", "category": "Effect" },
    { "id": 74, "name": "Smoke Brush", "category": "Effect" },
    { "id": 75, "name": "Cosmic / Galactic", "category": "Fantasy" },
    { "id": 76, "name": "Dreamcore", "category": "Fantasy" },
    { "id": 77, "name": "Vapor Art", "category": "Digital" },
    { "id": 78, "name": "Brutalist Surrealism", "category": "Hybrid" },
    { "id": 79, "name": "Fantasy Illustration", "category": "Fantasy" },
    { "id": 80, "name": "Magical Realism", "category": "Fantasy" },
    { "id": 81, "name": "Sci-fi Illustration", "category": "Fantasy" },
    { "id": 82, "name": "Comic Book", "category": "Comics" },
    { "id": 83, "name": "Manga", "category": "Comics" },
    { "id": 84, "name": "Anime Style", "category": "Comics" },
    { "id": 85, "name": "Ukiyo-e", "category": "Cultural - Japanese" },
    { "id": 86, "name": "Tibetan Thangka", "category": "Cultural - Himalayan" },
    { "id": 87, "name": "Indian Miniature", "category": "Cultural - Indian" },
    { "id": 88, "name": "Mughal Art", "category": "Cultural - Indian" },
    { "id": 89, "name": "Persian Illumination", "category": "Cultural - Middle Eastern" },
    { "id": 90, "name": "Islamic Geometric", "category": "Cultural - Middle Eastern" },
    { "id": 91, "name": "African Tribal", "category": "Cultural - African" },
    { "id": 92, "name": "Aboriginal Dot Painting", "category": "Cultural - Australian" },
    { "id": 93, "name": "Chinese Brush Painting", "category": "Cultural - Chinese" },
    { "id": 94, "name": "Korean Minhwa", "category": "Cultural - Korean" },
    { "id": 95, "name": "Japanese Sumi-e", "category": "Cultural - Japanese" },
    { "id": 96, "name": "Aztec / Mayan Inspired", "category": "Cultural - Mesoamerican" },
    { "id": 97, "name": "Scandinavian Folk", "category": "Cultural - European" },
    { "id": 98, "name": "Celtic Knotwork", "category": "Cultural - European" },
    { "id": 99, "name": "Indigenous American Pattern", "category": "Cultural - American" },
    { "id": 100, "name": "Gothic Medieval", "category": "Historical" }
  ]
}







{
  "artStyles": [
    { "value": "abstract", "label": "Abstract", "category": "Modern" },
    { "value": "impressionism", "label": "Impressionism", "category": "Classical" },
    { "value": "surrealism", "label": "Surrealism", "category": "Modern" },
    { "value": "cubism", "label": "Cubism", "category": "Modern" },
    { "value": "expressionism", "label": "Expressionism", "category": "Modern" },
    { "value": "realism", "label": "Realism", "category": "Classical" },
    { "value": "hyperrealism", "label": "Hyperrealism", "category": "Modern" },
    { "value": "minimalism", "label": "Minimalism", "category": "Contemporary" },
    { "value": "pop_art", "label": "Pop Art", "category": "Modern" },
    { "value": "modernism", "label": "Modernism", "category": "Modern" },
    { "value": "postmodernism", "label": "Postmodernism", "category": "Contemporary" },
    { "value": "art_nouveau", "label": "Art Nouveau", "category": "Classical" },
    { "value": "art_deco", "label": "Art Deco", "category": "Classical" },
    { "value": "baroque", "label": "Baroque", "category": "Historical" },
    { "value": "rococo", "label": "Rococo", "category": "Historical" },
    { "value": "renaissance", "label": "Renaissance", "category": "Historical" },
    { "value": "neoclassicism", "label": "Neoclassicism", "category": "Historical" },
    { "value": "romanticism", "label": "Romanticism", "category": "Historical" },
    { "value": "futurism", "label": "Futurism", "category": "Modern" },
    { "value": "dadaism", "label": "Dadaism", "category": "Modern" },
    { "value": "fauvism", "label": "Fauvism", "category": "Modern" },
    { "value": "pointillism", "label": "Pointillism", "category": "Modern" },
    { "value": "symbolism", "label": "Symbolism", "category": "Modern" },
    { "value": "naive_art", "label": "Naïve Art", "category": "Modern" },
    { "value": "constructivism", "label": "Constructivism", "category": "Modern" },
    { "value": "bauhaus", "label": "Bauhaus", "category": "Modern" },
    { "value": "suprematism", "label": "Suprematism", "category": "Modern" },
    { "value": "vorticism", "label": "Vorticism", "category": "Modern" },
    { "value": "brutalism", "label": "Brutalism", "category": "Contemporary" },
    { "value": "conceptual_art", "label": "Conceptual Art", "category": "Contemporary" },
    { "value": "kinetic_art", "label": "Kinetic Art", "category": "Contemporary" },
    { "value": "digital_glitch", "label": "Digital Glitch", "category": "Digital" },
    { "value": "vaporwave", "label": "Vaporwave", "category": "Digital" },
    { "value": "cyberpunk", "label": "Cyberpunk", "category": "Digital" },
    { "value": "steampunk", "label": "Steampunk", "category": "Fantasy" },
    { "value": "sci_fi_retro", "label": "Sci-fi Retro", "category": "Fantasy" },
    { "value": "synthwave", "label": "Synthwave", "category": "Digital" },
    { "value": "pixel_art", "label": "Pixel Art", "category": "Digital" },
    { "value": "low_poly", "label": "Low Poly", "category": "Digital" },
    { "value": "isometric", "label": "Isometric", "category": "Digital" },
    { "value": "flat_design", "label": "Flat Design", "category": "Digital" },
    { "value": "3d_rendered", "label": "3D Rendered", "category": "Digital" },
    { "value": "photorealism", "label": "Photorealism", "category": "Modern" },
    { "value": "generative_art", "label": "Generative Art", "category": "AI" },
    { "value": "ai_collage", "label": "AI Collage", "category": "AI" },
    { "value": "data_art", "label": "Data-Driven Art", "category": "AI" },
    { "value": "neural_dream", "label": "Neural Dream", "category": "AI" },
    { "value": "gan_art", "label": "GAN Art", "category": "AI" },
    { "value": "motion_blur", "label": "Motion Blur Style", "category": "Effect" },
    { "value": "chromatic_aberration", "label": "Chromatic Aberration", "category": "Effect" },
    { "value": "watercolor", "label": "Watercolor", "category": "Medium-Based" },
    { "value": "oil_painting", "label": "Oil Painting", "category": "Medium-Based" },
    { "value": "charcoal", "label": "Charcoal Sketch", "category": "Medium-Based" },
    { "value": "pencil_drawing", "label": "Pencil Drawing", "category": "Medium-Based" },
    { "value": "ink_wash", "label": "Ink Wash", "category": "Medium-Based" },
    { "value": "gouache", "label": "Gouache", "category": "Medium-Based" },
    { "value": "pastel", "label": "Pastel", "category": "Medium-Based" },
    { "value": "acrylic", "label": "Acrylic", "category": "Medium-Based" },
    { "value": "spray_paint", "label": "Spray Paint / Graffiti", "category": "Street" },
    { "value": "collage
