# Generated by Django 5.1.7 on 2025-12-17 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('service', models.CharField(default='runware', max_length=64)),
                ('model', models.CharField(default='google:4@1', max_length=128)),
                ('s3_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sculptures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SculptureImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=128)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(default='image/png', max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('angle_number', models.IntegerField(blank=True, null=True)),
                ('sculpture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sculpture.sculpture')),
            ],
            options={
                'ordering': ['angle_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sculpture',
            index=models.Index(fields=['user', '-created_at'], name='sculpture_s_user_id_4acb81_idx'),
        ),
        migrations.AddIndex(
            model_name='sculpture',
            index=models.Index(fields=['job_id'], name='sculpture_s_job_id_0cc251_idx'),
        ),
        migrations.AddIndex(
            model_name='sculpture',
            index=models.Index(fields=['status'], name='sculpture_s_status_e37b63_idx'),
        ),
        migrations.AddIndex(
            model_name='sculptureimage',
            index=models.Index(fields=['job_id'], name='sculpture_s_job_id_e09c42_idx'),
        ),
        migrations.AddIndex(
            model_name='sculptureimage',
            index=models.Index(fields=['sculpture', 'angle_number'], name='sculpture_s_sculptu_9ba174_idx'),
        ),
    ]
