# Generated by Django 5.1.7 on 2025-12-14 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='created', max_length=50)),
                ('is_shared', models.BooleanField(default=False)),
                ('s3_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sculptures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SculptureImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=128)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(default='image/png', max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('angle_number', models.IntegerField(blank=True, null=True)),
                ('sculpture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sculpture.sculpture')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job_id'], name='sculpture_s_job_id_e09c42_idx')],
            },
        ),
    ]
