# Generated by Django 5.1.7 on 2025-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('extracted_colors', models.JSONField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand_assets',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id'], name='brand_asset_user_id_cf56a1_idx'), models.Index(fields=['asset_id'], name='brand_asset_asset_i_b10862_idx'), models.Index(fields=['uploaded_at'], name='brand_asset_uploade_0b047c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('prompt', models.TextField()),
                ('campaign_goal', models.TextField()),
                ('tone', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
                ('aspect_ratio', models.CharField(default='1:1', max_length=20)),
                ('num_outputs', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=50)),
                ('materials', models.JSONField(blank=True, null=True)),
                ('text_suggestions', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='marketing_m_user_id_d01a27_idx'), models.Index(fields=['request_id'], name='marketing_m_request_46d721_idx'), models.Index(fields=['status'], name='marketing_m_status_aa3957_idx'), models.Index(fields=['created_at'], name='marketing_m_created_4156fa_idx')],
            },
        ),
    ]
