# Generated by Django 5.1.7 on 2025-07-16 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0011_audio_description_audio_genre_audio_track_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAudio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_audios', models.ManyToManyField(blank=True, related_name='liked_by_meta_audios', to='gallery.audio')),
                ('starred_audios', models.ManyToManyField(blank=True, related_name='starred_by_meta_audios', to='gallery.audio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Audio',
                'verbose_name_plural': 'Meta Audios',
                'db_table': 'meta_audios',
                'indexes': [models.Index(fields=['user'], name='meta_audios_user_id_aa34a3_idx')],
            },
        ),
    ]
