# Generated by Django 5.1.7 on 2025-05-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='canvas_ratio',
            field=models.CharField(blank=True, choices=[('9:16', '9:16'), ('16:9', '16:9'), ('1:1', '1:1'), ('4:3', '4:3'), ('5:4', '5:4'), ('3:2', '3:2'), ('2:3', '2:3'), ('2:1', '2:1'), ('1:2', '1:2')], default='16:9', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='S', max_length=255),
        ),
    ]
