# Generated by Django 5.1.7 on 2025-04-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_collection_options_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='gallery.image'),
        ),
    ]
