# Generated by Django 5.1.7 on 2025-07-24 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(choices=[('personal_painter', 'Personal Painter'), ('style_transfer', 'Style Transfer'), ('dream_visualizer', 'Dream Visualizer'), ('image_meta_gen', 'Image Metadata Generation'), ('replicate_style_transfer', 'Replicate Style Transfer'), ('replicate_iconic_art', 'Replicate Iconic Art'), ('reimagine_art', 'Reimagine Art'), ('runware_flux_tools', 'Runware FLUX Tools'), ('image_to_video', 'Image to Video'), ('runware_image_to_video', 'Runware Image to Video'), ('runware_text_to_video', 'Runware Text to Video'), ('painter_chat', 'Painter Chat'), ('dream_visualizer_chat', 'Dream Visualizer Chat'), ('vizzy', 'Vizzy Voice Assistant'), ('moodboard', 'Moodboard Creation'), ('poster', 'Poster Generation'), ('brand_asset', 'Brand Asset Creation'), ('mindscape', 'Mindscape'), ('book_to_frames', 'Book to Frames'), ('visual_journal', 'Visual Journal'), ('story_visualizer', 'Story Visualizer'), ('text_visualization', 'Text Visualization'), ('audio_processing', 'Audio Processing'), ('embedding', 'Embedding Generation'), ('onboard', 'AI Onboarding'), ('storyboard', 'Storyboard Creation')], max_length=50, unique=True)),
                ('base_credits', models.PositiveIntegerField()),
                ('per_unit_credits', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('tier_1_limit', models.PositiveIntegerField(default=0)),
                ('tier_1_price', models.PositiveIntegerField(default=0)),
                ('tier_2_price', models.PositiveIntegerField(default=0)),
                ('tier_3_price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Pricing',
                'verbose_name_plural': 'Feature Pricing',
                'db_table': 'feature_pricing',
            },
        ),
        migrations.CreateModel(
            name='DailyUserStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_ai_requests', models.PositiveIntegerField(default=0)),
                ('unique_features_used', models.PositiveIntegerField(default=0)),
                ('total_credits_spent', models.PositiveIntegerField(default=0)),
                ('total_session_time', models.DurationField(blank=True, null=True)),
                ('feature_usage_breakdown', models.JSONField(default=dict)),
                ('category_usage_breakdown', models.JSONField(default=dict)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily User Statistics',
                'verbose_name_plural': 'Daily User Statistics',
                'db_table': 'daily_user_stats',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_user__user_id_54fc3f_idx'), models.Index(fields=['date'], name='daily_user__date_976b62_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(choices=[('personal_painter', 'Personal Painter'), ('style_transfer', 'Style Transfer'), ('dream_visualizer', 'Dream Visualizer'), ('image_meta_gen', 'Image Metadata Generation'), ('replicate_style_transfer', 'Replicate Style Transfer'), ('replicate_iconic_art', 'Replicate Iconic Art'), ('reimagine_art', 'Reimagine Art'), ('runware_flux_tools', 'Runware FLUX Tools'), ('image_to_video', 'Image to Video'), ('runware_image_to_video', 'Runware Image to Video'), ('runware_text_to_video', 'Runware Text to Video'), ('painter_chat', 'Painter Chat'), ('dream_visualizer_chat', 'Dream Visualizer Chat'), ('vizzy', 'Vizzy Voice Assistant'), ('moodboard', 'Moodboard Creation'), ('poster', 'Poster Generation'), ('brand_asset', 'Brand Asset Creation'), ('mindscape', 'Mindscape'), ('book_to_frames', 'Book to Frames'), ('visual_journal', 'Visual Journal'), ('story_visualizer', 'Story Visualizer'), ('text_visualization', 'Text Visualization'), ('audio_processing', 'Audio Processing'), ('embedding', 'Embedding Generation'), ('onboard', 'AI Onboarding'), ('storyboard', 'Storyboard Creation')], max_length=50)),
                ('feature_category', models.CharField(choices=[('image_generation', 'Image Generation'), ('style_transfer', 'Style Transfer'), ('image_editing', 'Image Editing'), ('video_generation', 'Video Generation'), ('text_processing', 'Text Processing'), ('chat_ai', 'AI Chat'), ('audio_processing', 'Audio Processing'), ('visualization', 'Data Visualization'), ('creative_tools', 'Creative Tools')], max_length=30)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('endpoint_path', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('credit_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_usage_records', to='credits.creditaioperation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Usage',
                'verbose_name_plural': 'Feature Usage Records',
                'db_table': 'feature_usage',
                'indexes': [models.Index(fields=['user', 'created_at'], name='feature_usa_user_id_9da78f_idx'), models.Index(fields=['feature_name', 'created_at'], name='feature_usa_feature_d67420_idx'), models.Index(fields=['status'], name='feature_usa_status_ad8b8f_idx'), models.Index(fields=['user', 'feature_name'], name='feature_usa_user_id_f11d7a_idx'), models.Index(fields=['session_id'], name='feature_usa_session_b70a02_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile App'), ('api', 'Direct API'), ('desktop', 'Desktop App')], default='web', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('total_ai_features_used', models.PositiveIntegerField(default=0)),
                ('total_credits_spent', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['user', 'start_time'], name='user_sessio_user_id_c66047_idx'), models.Index(fields=['session_id'], name='user_sessio_session_e62ba3_idx'), models.Index(fields=['is_active'], name='user_sessio_is_acti_1b3cb1_idx')],
            },
        ),
    ]
