# Generated by Django 5.1.7 on 2025-12-12 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequentialArtwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_iterations', models.IntegerField(default=0)),
                ('sequence_images', models.JSONField(default=list, help_text='List of image URLs in sequence order')),
                ('s3_image_keys', models.JSONField(default=list, help_text='List of S3 keys for each image')),
                ('first_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('last_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('conversation_history', models.JSONField(default=dict, help_text='Chat conversation history')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequential_artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequentialArtworkIteration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iteration_number', models.IntegerField()),
                ('user_prompt', models.TextField()),
                ('assistant_response', models.TextField()),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('reference_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_image_url', models.URLField(max_length=1000)),
                ('generated_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('s3_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('s3_image_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='sequential_artwork.sequentialartwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_iterations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['iteration_number'],
            },
        ),
        migrations.AddIndex(
            model_name='sequentialartwork',
            index=models.Index(fields=['user', '-created_at'], name='sequential__user_id_ce28f5_idx'),
        ),
        migrations.AddIndex(
            model_name='sequentialartworkiteration',
            index=models.Index(fields=['user', 'is_saved'], name='sequential__user_id_0b783b_idx'),
        ),
        migrations.AddIndex(
            model_name='sequentialartworkiteration',
            index=models.Index(fields=['artwork', 'iteration_number'], name='sequential__artwork_c5e826_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequentialartworkiteration',
            unique_together={('artwork', 'iteration_number')},
        ),
    ]
