# Generated by Django 5.1.7 on 2025-12-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckovizComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('before_filename', models.CharField(blank=True, max_length=1024)),
                ('after_filename', models.CharField(blank=True, max_length=1024)),
                ('deckoviz_variant', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('halo_color', models.CharField(blank=True, max_length=64, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('placement_instructions', models.TextField(blank=True, null=True)),
                ('s3_before_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_before_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_after_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_after_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
