# Generated by Django 5.1.7 on 2025-06-21 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_image_description_image_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favourite_collections', models.ManyToManyField(blank=True, related_name='favourited_by_meta_collections', to='gallery.collection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Collection',
                'verbose_name_plural': 'Meta Collections',
                'db_table': 'meta_collections',
                'indexes': [models.Index(fields=['user'], name='meta_collec_user_id_e6889e_idx')],
            },
        ),
    ]
