# Generated by Django 5.1.7 on 2025-06-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_dailycuration'),
        ('metacollections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metacollection',
            name='starred_collections',
            field=models.ManyToManyField(blank=True, related_name='starred_by_meta_collections', to='gallery.collection'),
        ),
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='gallery.collection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_shared_to_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'shared_with')},
            },
        ),
    ]
