# Generated by Django 5.1.7 on 2025-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_audio_audio_alter_collection_music'),
        ('metacollections', '0002_metacollection_starred_collections_sharedcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacollection',
            name='liked_collections',
            field=models.ManyToManyField(blank=True, related_name='liked_by_meta_collections', to='gallery.collection'),
        ),
    ]
