# Generated by Django 5.1.7 on 2025-07-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('gallery', '0005_image_description_image_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='MetaImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_images', models.ManyToManyField(blank=True, related_name='liked_by_meta_images', to='gallery.image')),
                ('starred_images', models.ManyToManyField(blank=True, related_name='starred_by_meta_images', to='gallery.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Image',
                'verbose_name_plural': 'Meta Images',
                'db_table': 'meta_images',
                'indexes': [models.Index(fields=['user'], name='meta_image_user_id_idx')],
            },
        ),
    ] 