# Generated by Django 5.1.7 on 2025-07-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaimages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metaimage',
            new_name='meta_images_user_id_bb9498_idx',
            old_name='meta_image_user_id_idx',
        ),
    ]
