TRANSITION_EFFECT_CHOICES = [
    ('Fade In', 'Fade In'),
    ('Fade Out', 'Fade Out'),
    ('Slide Left', 'Slide Left'),
    ('Slide Right', 'Slide Right'),
    ('Slide Up', 'Slide Up'),
    ('Slide Down', 'Slide Down'),
    ('Zoom In', 'Zoom In'),
    ('Zoom Out', 'Zoom Out'),
    ('Flip Horizontal', 'Flip Horizontal'),
    ('Flip Vertical', 'Flip Vertical'),
    ('Rotate', 'Rotate'),
    ('Bounce', 'Bounce'),
    ('Elastic', 'Elastic'),
    ('Pulse', 'Pulse'),
    ('Shake', 'Shake'),
    ('Swing', 'Swing'),
    ('Wobble', 'Wobble'),
    ('Jelly', 'Jelly'),
    ('Light Speed', 'Light Speed'),
    ('Roll In', 'Roll In'),
]