"""
Utility for handling TV-Mobile app pairing in the mobile app
"""

import json
import time
import requests
from typing import Dict, Optional, Any, Union
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mobile_pairing")

class MobilePairingClient:
    """
    Client for handling TV-Mobile app pairing in the mobile app.
    This handles scanning QR codes and pairing with the TV app.
    """
    
    def __init__(self, auth_token: str = None):
        """
        Initialize the pairing client with authentication token.
        
        Args:
            auth_token (str): Authentication token for the mobile app user
        """
        self.auth_token = auth_token
        self.current_room_id = None
        
    def parse_qr_code_data(self, qr_data: str) -> Dict[str, Any]:
        """
        Parse QR code data from the TV app.
        
        Args:
            qr_data (str): QR code content scanned by the mobile app
            
        Returns:
            Dict: Parsed QR code data
        """
        try:
            data = json.loads(qr_data)
            
            # Validate required fields
            required_fields = ["action", "device_id", "api_endpoint"]
            for field in required_fields:
                if field not in data:
                    raise ValueError(f"QR code data missing required field: {field}")
                    
            # Validate action type
            if data["action"] != "pair_room":
                raise ValueError(f"Unsupported QR code action: {data['action']}")
                
            # Check for expiration
            if "timestamp" in data:
                current_time = int(time.time())
                qr_time = data["timestamp"]
                # Check if QR code is older than 5 minutes
                if current_time - qr_time > 300:
                    raise ValueError("QR code has expired. Please refresh the TV app.")
                    
            return data
            
        except json.JSONDecodeError:
            raise ValueError("Invalid QR code format. Not a valid JSON.")
            
    def pair_with_tv(self, qr_data: str, room_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Pair with a TV app after scanning the QR code.
        
        Args:
            qr_data (str): QR code content scanned by the mobile app
            room_id (str, optional): Custom room ID to use. If None, a new one will be generated by the server.
            
        Returns:
            Dict: Response from the pairing API
        """
        parsed_data = self.parse_qr_code_data(qr_data)
        
        # Extract data
        device_id = parsed_data["device_id"]
        api_endpoint = parsed_data["api_endpoint"]
        
        # Prepare headers
        headers = {"Content-Type": "application/json"}
        if self.auth_token:
            headers["Authorization"] = f"Bearer {self.auth_token}"
        
        # Prepare payload
        payload = {
            "device_id": device_id,
            "room_id": room_id or ""  # Server will generate a room ID if empty
        }
        
        try:
            # Make the API call to pair
            response = requests.post(
                api_endpoint, 
                json=payload,
                headers=headers
            )
            
            # Check for success
            if response.status_code == 200:
                data = response.json()
                # Extract room ID from response message
                if "room_id" in data:
                    self.current_room_id = data["room_id"]
                elif "message" in data:
                    # Try to extract room ID from message
                    import re
                    match = re.search(r"room ([a-zA-Z0-9-]+)", data["message"])
                    if match:
                        self.current_room_id = match.group(1)
                
                logger.info(f"Successfully paired with TV. Room ID: {self.current_room_id}")
                return data
            else:
                # Handle error
                error_msg = f"Pairing failed with status code {response.status_code}"
                try:
                    error_data = response.json()
                    if "detail" in error_data:
                        error_msg = f"Pairing failed: {error_data['detail']}"
                except:
                    pass
                    
                logger.error(error_msg)
                raise Exception(error_msg)
                
        except requests.RequestException as e:
            logger.error(f"Error connecting to pairing API: {str(e)}")
            raise Exception(f"Connection error: {str(e)}")
            
    def connect_to_websocket(self, base_ws_url: str) -> str:
        """
        Get the WebSocket URL to connect to after successful pairing.
        
        Args:
            base_ws_url (str): Base WebSocket URL (e.g., "wss://example.com/ws/mobile")
            
        Returns:
            str: Complete WebSocket URL with room ID and authentication
        """
        if not self.current_room_id:
            raise ValueError("Not paired with any TV. Pair with a TV first.")
            
        # Add parameters to WebSocket URL
        params = [f"room={self.current_room_id}"]
        if self.auth_token:
            params.append(f"token={self.auth_token}")
            
        return f"{base_ws_url}?{'&'.join(params)}"
