# Generated by Django 5.1.7 on 2025-12-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, max_length=1024)),
                ('original_image_uuid', models.CharField(blank=True, max_length=256)),
                ('edited_filename', models.CharField(blank=True, max_length=1024)),
                ('transformation_type', models.CharField(choices=[('room_edit', 'Room Edit'), ('deckoviz_placement', 'Deckoviz Placement')], default='room_edit', max_length=64)),
                ('edit_instructions', models.TextField(blank=True, null=True)),
                ('style_hint', models.CharField(blank=True, max_length=128, null=True)),
                ('placement_instructions', models.TextField(blank=True, null=True)),
                ('deckoviz_variant', models.CharField(blank=True, max_length=64, null=True)),
                ('size_variant', models.CharField(blank=True, max_length=64, null=True)),
                ('halo_color', models.CharField(blank=True, max_length=128, null=True)),
                ('frame_material', models.CharField(blank=True, max_length=128, null=True)),
                ('preserve_room', models.BooleanField(default=True)),
                ('s3_original_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_original_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_output_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_output_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('change_log_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('change_log_s3_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('change_log_s3_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('metadata_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('metadata_s3_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('metadata_s3_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=64)),
                ('service', models.CharField(default='runware', max_length=64)),
                ('model', models.CharField(default='google:4@1', max_length=128)),
                ('parsed_changes', models.JSONField(blank=True, default=dict)),
                ('deckoviz_specs', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('share', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='before_afte_user_id_4b8d05_idx'), models.Index(fields=['session_id'], name='before_afte_session_7b85c9_idx'), models.Index(fields=['job_id'], name='before_afte_job_id_220776_idx'), models.Index(fields=['status'], name='before_afte_status_b3e00d_idx')],
            },
        ),
    ]
