# Generated by Django 5.1.7 on 2025-12-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('before_filename', models.CharField(blank=True, max_length=1024)),
                ('after_filename', models.CharField(blank=True, max_length=1024)),
                ('transformation_type', models.CharField(choices=[('deckoviz', 'Deckoviz'), ('general_edit', 'General Edit')], default='general_edit', max_length=64)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('edit_instructions', models.TextField(blank=True, null=True)),
                ('style_hint', models.CharField(blank=True, max_length=128, null=True)),
                ('s3_before_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_before_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_after_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('s3_after_key', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
