# Generated by Django 5.1.7 on 2025-12-07 03:38

import ckeditor.fields
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=256)),
                ('description', ckeditor.fields.RichTextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('delete_status', models.IntegerField(default=0)),
                ('images', models.ManyToManyField(blank=True, related_name='blogs_images', to='blogs.asset')),
                ('videos', models.ManyToManyField(blank=True, related_name='blogs_videos', to='blogs.asset')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blogs',
                'managed': True,
                'indexes': [models.Index(fields=['created_at'], name='idx_blog_created_at')],
            },
        ),
    ]
