# Generated by Django 5.1.7 on 2025-05-23 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_asset_alter_blog_images_alter_blog_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False),
        ),
    ]
