# Generated by Django 5.1.7 on 2025-12-07 03:40

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('transcription', 'Audio Transcription'), ('analysis', 'Transcript Analysis'), ('summarization', 'Text Summarization'), ('image_generation', 'Image Generation'), ('image_editing', 'Image Editing')], max_length=30, unique=True)),
                ('base_credits', models.PositiveIntegerField()),
                ('per_unit_credits', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Credit Pricing',
                'verbose_name_plural': 'Credit Pricing',
                'db_table': 'credit_pricing',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'db_table': 'plan_features',
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('credits', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Credit Package',
                'verbose_name_plural': 'Credit Packages',
                'db_table': 'credit_packages',
                'indexes': [models.Index(fields=['is_active'], name='credit_pack_is_acti_a99659_idx'), models.Index(fields=['name'], name='credit_pack_name_85ba2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('premium', 'Premium'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_price', models.CharField(help_text="Display price like '$299'", max_length=20)),
                ('price_suffix', models.CharField(default='/frame', help_text="Price suffix like '/month' or '/frame'", max_length=20)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, help_text="Short description like 'Perfect for your first smart art experience'", max_length=200)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order of plans')),
            ],
            options={
                'verbose_name': 'Credit Plan',
                'verbose_name_plural': 'Credit Plans',
                'db_table': 'credit_plans',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active'], name='credit_plan_is_acti_36d354_idx'), models.Index(fields=['plan_type'], name='credit_plan_plan_ty_b01d17_idx'), models.Index(fields=['is_popular'], name='credit_plan_is_popu_dbe308_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditAIOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('transcription', 'Audio Transcription'), ('analysis', 'Transcript Analysis'), ('summarization', 'Text Summarization'), ('image_generation', 'Image Generation'), ('image_editing', 'Image Editing')], max_length=30)),
                ('credits_used', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('operation_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ai_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit AI Operation',
                'verbose_name_plural': 'Credit AI Operations',
                'db_table': 'credit_ai_operations',
                'indexes': [models.Index(fields=['user'], name='credit_ai_o_user_id_e7799e_idx'), models.Index(fields=['operation_type'], name='credit_ai_o_operati_b00a47_idx'), models.Index(fields=['status'], name='credit_ai_o_status_077cb9_idx'), models.Index(fields=['created_at'], name='credit_ai_o_created_082e45_idx'), models.Index(fields=['operation_id'], name='credit_ai_o_operati_08a883_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('expiry', 'Expiry')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transactions',
                'indexes': [models.Index(fields=['user'], name='credit_tran_user_id_45804b_idx'), models.Index(fields=['transaction_type'], name='credit_tran_transac_0eee54_idx'), models.Index(fields=['created_at'], name='credit_tran_created_d7035f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_description', models.CharField(blank=True, help_text='Optional custom description for this feature in this plan', max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.planfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_associations', to='credits.creditplan')),
            ],
            options={
                'verbose_name': 'Plan Feature Association',
                'verbose_name_plural': 'Plan Feature Associations',
                'db_table': 'plan_feature_associations',
                'indexes': [models.Index(fields=['plan'], name='plan_featur_plan_id_3b220a_idx'), models.Index(fields=['feature'], name='plan_featur_feature_7bcd9d_idx')],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_credits', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
                'db_table': 'user_credits',
                'indexes': [models.Index(fields=['user'], name='user_credit_user_id_23679b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.creditplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
                'indexes': [models.Index(fields=['user'], name='user_subscr_user_id_3bc394_idx'), models.Index(fields=['plan'], name='user_subscr_plan_id_284bf8_idx'), models.Index(fields=['status'], name='user_subscr_status_deb44c_idx'), models.Index(fields=['start_date'], name='user_subscr_start_d_3b246d_idx'), models.Index(fields=['end_date'], name='user_subscr_end_dat_adeef7_idx')],
            },
        ),
    ]
