# Generated by Django 5.1.7 on 2025-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpackage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
