# Generated by Django 5.1.7 on 2025-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_creditpackage_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditpackage',
            index=models.Index(fields=['name'], name='credit_pack_name_85ba2f_idx'),
        ),
    ]
