# Generated by Django 5.1.7 on 2025-05-29 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('marketplace', '0002_price_canvas_ratio_price_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='gallery.image')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='marketplace.price')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
                'indexes': [models.Index(fields=['user'], name='carts_user_id_b1c689_idx')],
            },
        ),
    ]
