# Generated by Django 5.1.7 on 2025-12-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IterativeArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('final_image_url', models.TextField()),
                ('final_image_path', models.TextField(blank=True, null=True)),
                ('final_prompt', models.TextField()),
                ('conversation_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iterative_artworks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='iterative_a_user_id_cfce8e_idx'), models.Index(fields=['created_at'], name='iterative_a_created_89c958_idx')],
            },
        ),
        migrations.CreateModel(
            name='IterativeArtworkIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('user_prompt', models.TextField()),
                ('assistant_response', models.TextField()),
                ('reference_image_path', models.TextField(blank=True, null=True)),
                ('generated_image_url', models.TextField(blank=True, null=True)),
                ('generated_image_path', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('iteration_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='iterative_artwork.iterativeartwork')),
            ],
            options={
                'db_table': 'iterative_artwork_iterations',
                'ordering': ['iteration_number'],
                'indexes': [models.Index(fields=['user_id'], name='iterative_a_user_id_395590_idx'), models.Index(fields=['artwork_id'], name='iterative_a_artwork_083fa6_idx'), models.Index(fields=['iteration_number'], name='iterative_a_iterati_20c4b3_idx')],
            },
        ),
    ]
