# Generated by Django 5.1.7 on 2025-12-06 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Montage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=500)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('selecting_images', 'Selecting Images'), ('searching_music', 'Searching Music'), ('downloading_music', 'Downloading Music'), ('creating_video', 'Creating Video'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=50)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('music_style', models.CharField(blank=True, max_length=255, null=True)),
                ('music_tags', models.JSONField(blank=True, null=True)),
                ('selected_image_paths', models.JSONField(blank=True, null=True)),
                ('music_url', models.CharField(blank=True, max_length=500, null=True)),
                ('music_title', models.CharField(blank=True, max_length=255, null=True)),
                ('music_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('music_license', models.CharField(blank=True, max_length=500, null=True)),
                ('music_attribution', models.TextField(blank=True, null=True)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('video_duration', models.FloatField(blank=True, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('output_video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('total_images_uploaded', models.IntegerField(default=0)),
                ('images_used', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_montages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('montage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='ai_montage.montage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montage_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_montage_uploaded_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='montage',
            index=models.Index(fields=['user', '-created_at'], name='ai_montages_user_id_9c872d_idx'),
        ),
        migrations.AddIndex(
            model_name='montage',
            index=models.Index(fields=['status'], name='ai_montages_status_422506_idx'),
        ),
    ]
