# Generated by Django 5.1.7 on 2025-06-20 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('vocation', models.CharField(blank=True, max_length=255)),
                ('hobbies', models.TextField(blank=True)),
                ('passions', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('desired_states', models.TextField(blank=True)),
                ('personal_beliefs', models.TextField(blank=True)),
                ('life_principles', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True)),
                ('secondary_values', models.TextField(blank=True)),
                ('hopes_and_dreams', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
