# Generated by Django 5.1.7 on 2025-07-22 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0013_audio_music_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedCollections',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title for this curation', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this curation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this curation is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying curations')),
                ('collections', models.ManyToManyField(blank=True, related_name='curated_collections', to='gallery.collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collection_curations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curated Collections',
                'verbose_name_plural': 'Curated Collections',
                'db_table': 'curated_collections',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='curated_col_is_acti_29f662_idx'), models.Index(fields=['order'], name='curated_col_order_e60452_idx'), models.Index(fields=['created_at'], name='curated_col_created_86cf44_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuratedImages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title for this curation', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this curation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this curation is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying curations')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_image_curations', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='curated_images', to='gallery.image')),
            ],
            options={
                'verbose_name': 'Curated Images',
                'verbose_name_plural': 'Curated Images',
                'db_table': 'curated_images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='curated_ima_is_acti_c97651_idx'), models.Index(fields=['order'], name='curated_ima_order_c38842_idx'), models.Index(fields=['created_at'], name='curated_ima_created_c88643_idx')],
            },
        ),
    ]
