# Generated by Django 5.1.7 on 2025-12-07 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedCollections',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this curation is active')),
                ('collections', models.ManyToManyField(blank=True, related_name='curated_collections', to='gallery.collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collection_curations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curated Collections',
                'verbose_name_plural': 'Curated Collections',
                'db_table': 'curated_collections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='curated_col_is_acti_29f662_idx'), models.Index(fields=['created_at'], name='curated_col_created_86cf44_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuratedImages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this curation is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_image_curations', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='curated_images', to='gallery.image')),
            ],
            options={
                'verbose_name': 'Curated Images',
                'verbose_name_plural': 'Curated Images',
                'db_table': 'curated_images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='curated_ima_is_acti_c97651_idx'), models.Index(fields=['created_at'], name='curated_ima_created_c88643_idx')],
            },
        ),
    ]
