# Generated by Django 5.1.7 on 2025-07-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatedcollections',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curated Collections', 'verbose_name_plural': 'Curated Collections'},
        ),
        migrations.AlterModelOptions(
            name='curatedimages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curated Images', 'verbose_name_plural': 'Curated Images'},
        ),
        migrations.RemoveIndex(
            model_name='curatedcollections',
            name='curated_col_order_e60452_idx',
        ),
        migrations.RemoveIndex(
            model_name='curatedimages',
            name='curated_ima_order_c38842_idx',
        ),
        migrations.RemoveField(
            model_name='curatedcollections',
            name='description',
        ),
        migrations.RemoveField(
            model_name='curatedcollections',
            name='order',
        ),
        migrations.RemoveField(
            model_name='curatedcollections',
            name='title',
        ),
        migrations.RemoveField(
            model_name='curatedimages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='curatedimages',
            name='order',
        ),
        migrations.RemoveField(
            model_name='curatedimages',
            name='title',
        ),
    ]
